config/routes.rb
Scrumptious::Application.routes.draw do
  resources :projects do
    get 'settings'
    get 'members'
    get 'reports'
    get 'integrations'
    get 'backlog'
    get 'sprints'
    resources :stories
    resources :epics
  end

  devise_for :users

  resource :profiles

  get "dashboard/index"

  root :to => 'dashboard#index'

end

app/models/backlog.rb
class Backlog
  include Mongoid::Document
  field :title, type: String

  has_many :stories
  has_many :epics
  embedded_in :project
end

app/models/epic.rb
class Epic
  include Mongoid::Document
  field :title, type: String
  field :description, type: String

  belongs_to :backlog
end

app/models/project.rb
class Project
  include Mongoid::Document
  field :name, type: String
  field :description, type: String

  embeds_one :backlog

  after_create do |d|
    d.create_backlog :title => "#{d.name} - Backlog"
  end
end

app/models/sprint.rb
class Sprint
  include Mongoid::Document
end

app/models/story.rb
class Story
  include Mongoid::Document
  field :title, type: String
  field :point, type: Integer

  belongs_to :backlog
end

app/models/user.rb
class User
  include Mongoid::Document
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name

  ## Database authenticatable
  field :email,              :type => String, :default => ""
  field :encrypted_password, :type => String, :default => ""

  ## Recoverable
  field :reset_password_token,   :type => String
  field :reset_password_sent_at, :type => Time

  ## Rememberable
  field :remember_created_at, :type => Time

  ## Trackable
  field :sign_in_count,      :type => Integer, :default => 0
  field :current_sign_in_at, :type => Time
  field :last_sign_in_at,    :type => Time
  field :current_sign_in_ip, :type => String
  field :last_sign_in_ip,    :type => String

  ## Confirmable
  # field :confirmation_token,   :type => String
  # field :confirmed_at,         :type => Time
  # field :confirmation_sent_at, :type => Time
  # field :unconfirmed_email,    :type => String # Only if using reconfirmable

  ## Lockable
  # field :failed_attempts, :type => Integer, :default => 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    :type => String # Only if unlock strategy is :email or :both
  # field :locked_at,       :type => Time

  ## Token authenticatable
  # field :authentication_token, :type => String

  field :name, :type => String, :default => ""
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :authenticate_user!
  
  layout :choose_layout


  protected
  
  def choose_layout
  	if devise_controller?
  		"devise"
  	else
  		"application"
  	end
  end

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
  	@projects = Project.all
  end
end

app/controllers/epics_controller.rb
class EpicsController < ApplicationController
	def create
		@project = Project.find(params[:project_id])
		@story = @project.backlog.epics.create(params[:epic])
		redirect_to project_backlog_path(@project)
	end
end

app/controllers/profiles_controller.rb
require 'pp'

class ProfilesController < ApplicationController
	def show
		@user = current_user
	end

	def edit
		@user = current_user
	end

	def update
		@user = current_user

		pp params[:user]
		respond_to do |format|
	        if @user.update_attributes(params[:user])
	        	format.html { redirect_to profiles_path(@user), notice: 'Job was successfully updated.' }
	        else
	        	format.html { render action: "edit" }
	        end
        end
	end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @projects }
    end
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @project = Project.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/new
  # GET /projects/new.json
  def new
    @project = Project.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/1/edit
  def edit
    @project = Project.find(params[:id])
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(params[:project])

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render json: @project, status: :created, location: @project }
      else
        format.html { render action: "new" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /projects/1
  # PUT /projects/1.json
  def update
    @project = Project.find(params[:id])

    respond_to do |format|
      if @project.update_attributes(params[:project])
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project = Project.find(params[:id])
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url }
      format.json { head :no_content }
    end
  end

  def settings
    @project = Project.find(params[:project_id])
  end

  def members
    @project = Project.find(params[:project_id])
  end

  def reports
    @project = Project.find(params[:project_id])
  end

  def integrations
    @project = Project.find(params[:project_id])
  end

  def backlog
    @project = Project.find(params[:project_id])
  end

  def sprints
    @project = Project.find(params[:project_id])
  end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
	def create
		@project = Project.find(params[:project_id])
		@story = @project.backlog.stories.create(params[:story])
		redirect_to project_backlog_path(@project)
	end

	def show
		@project = Project.find(params[:project_id])
		@story = @project.backlog.stories.find(params[:id])
		
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/dashboard/index.html.haml
.page-header
  %h3 Dashboard

.row
  .col-lg-6.infobox
    .infobox-hdr
      %h4 My Projects
      .list-group
        - @projects.each do |p|
          %a.list-group-item{href: project_path(p)}
            %h4.list-group-item-heading= p.name
            %p.list-group-item-text= p.description
      %p
        %a.btn.btn-primary.btn-block{href: projects_path } Show all my projects
  
  .col-lg-6.infobox
    .infobox-hdr
      %h4 Activity Feed
    %p This is your activity feed. It will show you the latest activity within your projects.
    %p
      %a.btn.btn-default{href: "#"} View details »

app/views/layouts/application.html.haml
!!!
%html{lang: "en"}
  %head
    %meta{charset: "utf-8"}/
    %meta{content: "width=device-width, initial-scale=1.0", name: "viewport"}/
    %meta{content: "", name: "description"}/
    %meta{content: "", name: "author"}/
    %title Scrumptious
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    .navbar.navbar-inverse.navbar-fixed-top
      .container
        .navbar-header
          %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", type: "button"}
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.navbar-brand{href: root_path } Scrumptious
        .collapse.navbar-collapse
          = render 'shared/navbar_main'
          - if user_signed_in?
            = render 'shared/navbar_aux'
    .container
      = yield

app/views/layouts/devise.html.haml
!!!
%html{:lang => "en"}
  %head
    %meta{:charset => "utf-8"}/
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    %meta{:content => "", :name => "description"}/
    %meta{:content => "", :name => "author"}/
    %title Scrumptious
    = stylesheet_link_tag    "devise", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    .container
      = yield

app/views/profiles/edit.html.haml
.page-header
  %h3 Manage Profile

= form_for( @user, :url => profiles_path, :html => {:class => 'form-horizontal', :role => 'form'} )do |f|
  - if @user.errors.any?
    #error_explanation
      %h2= "#{pluralize(@project.errors.count, "error")} prohibited this project from being saved:"
      %ul
        - @project.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    = f.label :name, :class => 'col-lg-2 control-label'
    .col-lg-10
      = f.text_field :name, :class => 'form-control'
  .form-group
    = f.label :email, :class => 'col-lg-2 control-label'
    .col-lg-10
      = f.text_field :email, :class => 'form-control'
  .form-group
    .col-lg-offset-2.col-lg-10
      = f.submit 'Save', :class => 'btn btn-primary'
      = link_to 'Cancel', root_path, :class => 'btn btn-default'

app/views/profiles/show.html.haml
.page-header
  %h3= @user.name

app/views/projects/_form.html.haml
= form_for( @project, :html => {:class => 'form-horizontal', :role => 'form'} )do |f|
  - if @project.errors.any?
    #error_explanation
      %h2= "#{pluralize(@project.errors.count, "error")} prohibited this project from being saved:"
      %ul
        - @project.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    = f.label :name, :class => 'col-lg-2 control-label'
    .col-lg-10
      = f.text_field :name, :class => 'form-control'
  .form-group
    = f.label :description, :class => 'col-lg-2 control-label'
    .col-lg-10
      = f.text_area :description, :rows => 5, :class => 'form-control'
  .form-group
    .col-lg-offset-2.col-lg-10
      = f.submit 'Save', :class => 'btn btn-primary'
      = link_to 'Cancel', projects_path, :class => 'btn btn-default'

app/views/projects/_header.html.haml
.page-header
  %h3= @project.name

%p#notice= notice

%ul.nav.nav-tabs
  %li#show.active
    %a{href: project_path(@project)} Overview
  %li#settings
    %a{href: project_settings_path(@project) } Settings
  %li#members
    %a{href: project_members_path(@project) } Members
  %li#reports
    %a{href: project_reports_path(@project) } Reports
  %li#integrations
    %a{href: project_integrations_path(@project) } Integrations
  %li#backlog
    %a{href: project_backlog_path(@project) } Backlog
  %li#sprints
    %a{href: project_sprints_path(@project) } Sprints

:javascript
  $(function(){
    $('.nav-tabs li.active').removeClass('active');
    $('.nav-tabs li##{params[:action]}').addClass('active');
  });

app/views/projects/backlog.html.haml
= render 'header'


.row
  .col-lg-8.infobox
    .infobox-hdr
      %h4 Backlog
    - if @project.backlog.stories.count == 0 
      .alert.alert-info There are currently no stories in the backlog.      
      %a.btn.btn-default{href: "#"} View details »
    - else
      .list-group
        - @project.backlog.stories.each do |story|
          %a.list-group-item{href: project_story_path(@project, story)}
            %p.list-group-item-text
              .badge= story.point
              = story.title
  
  .col-lg-4.infobox
    .infobox-hdr
      %h4 Actions
    %p
      %a.btn.btn-primary.btn-sm.btn-block{href: "#", "data-toggle" => "modal", "data-target" => "#story-modal"} Create Story
      %a.btn.btn-primary.btn-sm.btn-block{href: "#", "data-toggle" => "modal", "data-target" => "#epic-modal"} Create Epic
      %a.btn.btn-primary.btn-sm.btn-block{href: "#"} Create Sprint


.modal#story-modal
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", type: "button"} ×
        %h4.modal-title Create Story
      .modal-body
        = form_for( [@project, Story.new], :html => {:class => 'form-horizontal', :role => 'form'} )do |f|
          .form-group
            = f.label :title, :class => 'col-lg-2 control-label'
            .col-lg-10
              = f.text_field :title, :class => 'form-control'
          .form-group
            = f.label :point, :class => 'col-lg-2 control-label'
            .col-lg-10
              = f.text_field :point, :class => 'form-control'
          .form-group
            .col-lg-offset-2.col-lg-10
              = f.submit 'Save', :class => 'btn btn-primary'
              %button.btn.btn-default{"data-dismiss" => "modal", type: "button"} Cancel


.modal#epic-modal
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", type: "button"} ×
        %h4.modal-title Create Epic
      .modal-body
        = form_for( [@project, Epic.new], :html => {:class => 'form-horizontal', :role => 'form'} )do |f|
          .form-group
            = f.label :title, :class => 'col-lg-2 control-label'
            .col-lg-10
              = f.text_field :title, :class => 'form-control'
          .form-group
            = f.label :description, :class => 'col-lg-2 control-label'
            .col-lg-10
              = f.text_area :description, :rows => 5, :class => 'form-control'
          .form-group
            .col-lg-offset-2.col-lg-10
              = f.submit 'Save', :class => 'btn btn-primary'
              %button.btn.btn-default{"data-dismiss" => "modal", type: "button"} Cancel

app/views/projects/edit.html.haml
.page-header
  %h3 Edit Project

= render 'form'

app/views/projects/index.html.haml
.page-header
  .row
    .col-lg-8
      %h3 Projects
    .col-lg-4
      .pull-right
        = link_to 'New Project', new_project_path, :class => 'btn btn-default'

- if @projects.count == 0
  %p
    There are no Projects yet. 
    = link_to 'Create one', new_project_path
- else
  %table.table
    %tr
      %th Name
      %th Description
      %th
      %th
    - @projects.each do |project|
      %tr
        %td= link_to project.name, project
        %td= project.description
        %td= link_to 'Edit', edit_project_path(project)
        %td= link_to 'Destroy', project, :method => :delete, :data => { :confirm => 'Are you sure?' }

app/views/projects/integrations.html.haml
= render 'header'

app/views/projects/members.html.haml
= render 'header'

app/views/projects/new.html.haml
.page-header
  %h3 New Project

= render 'form'

app/views/projects/reports.html.haml
= render 'header'

app/views/projects/settings.html.haml
= render 'header'

app/views/projects/show.html.haml
= render 'header'

.row
  .col-lg-6.infobox
    .infobox-hdr
      %h4 Project Profile
    %p= @project.description
    %p
      %a.btn.btn-default{href: "#"} View details »
  .col-lg-6.infobox
    .infobox-hdr
      %h4 Velocity
    %p Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui.
    %p
      %a.btn.btn-default{href: "#"} View details »
  .col-lg-6.infobox
    .infobox-hdr
      %h4 Reports
    %p Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui.
    %p
      %a.btn.btn-default{href: "#"} View details »
  .col-lg-6.infobox
    .infobox-hdr
      %h4 Members
    %p Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui.
    %p
      %a.btn.btn-default{href: "#"} View details »

app/views/projects/sprints.html.haml
= render 'header'

app/views/shared/_navbar_aux.html.haml
%ul.nav.navbar-nav.navbar-right
  %li.dropdown
    %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
      %span.glyphicon.glyphicon-user
      %b.caret
    %ul.dropdown-menu
      %li
        %a{:href => profiles_path(current_user)} Profile
      %li
        %a{:href => edit_profiles_path(current_user)} Manage Profile
      %li.divider
      %li= link_to('Logout', destroy_user_session_path, :method => :delete)

app/views/shared/_navbar_main.html.haml
%ul.nav.navbar-nav
  %li.active= link_to 'Dashboard', dashboard_index_path
  %li.dropdown
    %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
      Projects
      %b.caret
    %ul.dropdown-menu
      %li
        %a{:href => projects_path } View All

app/views/stories/show.html.haml
.page-header
  %h3= @story.title